import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DataProvider from "@/context/dataContext";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` flex flex-col min-h-scree ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DataProvider>
       
            <Header />

            {/* Main cresce para preencher o espaço */}
            <main className="flex-1">{children}</main>
            <footer className="mt-60">
              <Footer />
            </footer>
         
        </DataProvider>
      </body>
    </html>
  );
}
